title: Pulkit Gangwar
logo: /assets/img/logo.png
description: Hi I am Pulkit Gangwar , I am an experienced web developer. I have previously worked on e-commerce and educational tech projects. I am specialized in html ,css ,javascript ,react.js ,next.js ,node.js ,express.js ,postgres ,typescript
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
